
name: Build smtest reports2 application (Windows)

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.9.8' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build with pyinstaller
      run: |
        cd releasefiles/reports2
        pyinstaller -F --noupx --onefile --clean --distpath dist/win sm-reports2.py

    - uses: actions/upload-artifact@v2
      with:
        name: "sm-reports2-win"
        path: releasefiles/reports2/dist/win

    