
name: Build smtest reports2 application

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build reports application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: releasefiles/reports2

    - uses: actions/upload-artifact@v2
      with:
        name: "sm-reports2"
        path: releasefiles/reports2/dist/windows