
name: Build smtest reports2 application (Linux)

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
       matrix:
         os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.9.8' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install requests

    - name: Build with pyinstaller
      run: |
        cd releasefiles/reports2
        pyinstaller -F --noupx --onefile --clean sm-reports2.py

    - name: Grant execute permission on executable
      run: chmod +x dist/*

    - uses: actions/upload-artifact@v2
      with:
        name: sm-reports2-${{ matrix.os }}
        path: releasefiles/reports2/dist

    
